version: 2.1
jobs:
  run_and_test:
    docker:
      - image: circleci/node:14
        environment:
          MY_ENV_VAR_1: my-value-1
          MY_ENV_VAR_2: my-value-2
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules

workflows:
  test_my_app:
    jobs:
      - run_and_test
      
