version: 2.1
jobs:
  run_and_test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install
      - run:
          command: npm test
          name: Run tests
      
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules

workflows:
  test_my_app:
    jobs:
      - run_and_test
      
